on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'
  workflow_dispatch:

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm config set registry https://registry.npmjs.org/
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#      - run: |
#          sudo cp kubectl /usr/local/bin
#          sudo chmod 755 /usr/local/bin/kubectl
      - uses: ./
        with:
          ak: ${{ secrets.ACCESSKEY }}
          sk: ${{ secrets.SECRETACCESSKEY }}
          region: "af-south-1"
          project_id: "eecc7ec81ad346adbcde0a07fa343cb0"   # replace your project_id
          cluster_id: "8817579e-f98a-11ee-990c-0255ac1000eb"    # replace your cluster_id
      - run: |
          kubectl version --client
          kubectl config view
          kubectl cluster-info
          kubectl get pod,svc --all-namespaces
